# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly
env:
  matrix:
    - JULIA_CUBA_BUILD_SOURCE=true
    - JULIA_CUBA_BUILD_SOURCE=false
notifications:
  email: false
git:
  depth: 99999999

after_success:
 - julia -e 'using Pkg; cd(Pkg.dir("Cuba")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();
                                               Pkg.build("Cuba")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
